## Localization strings
extends Node

var current_lang: String = "zh"

var strings: Dictionary = {
	"zh": {
		"title": "骰运牌途",
		"subtitle": "DICE & DESTINY",
		"desc": "Roguelike 卡牌骰子战斗游戏",
		"begin": "开始冒险",
		"settings": "设置",
		"quit": "退出",
		"settings_title": "设置",
		"display_mode": "显示模式",
		"fullscreen": "全屏",
		"windowed": "窗口化",
		"language": "语言",
		"back": "返回",
		"end_turn": "结束回合 [E]",
		"hand": "手牌:",
		"dice_pool": "骰子池:",
		"floor": "第 %d 层 / 共 %d 层",
		"hp": "生命",
		"energy": "能量: %d/%d",
		"armor": "护甲: %d",
		"victory_title": "胜利!",
		"victory_sub": "恶魔领主已被击败!",
		"game_over": "你倒下了...",
		"retry": "再试一次",
		"main_menu": "主菜单",
		"battle_log_turn": "=== 第 %d 回合 ===",
		"not_enough_energy": "能量不足!",
		"deals_damage": "%s 造成 %d 点伤害! (骰子: +%d)",
		"gains_armor": "%s 获得 %d 点护甲 (骰子: +%d)",
		"fireball_hits": "火球术命中全体 %d 点! (骰子: +%d)",
		"ice_shard_hits": "冰晶: %d 点伤害 + 冻结! (骰子: +%d)",
		"healed": "恢复 %d 点生命 (骰子: +%d)",
		"regen": "每回合恢复 %d 点生命，持续3回合",
		"reroll": "重掷所有骰子并 +%d!",
		"loaded": "将一颗骰子设为6!",
		"enemy_frozen": "%s 被冻结了!",
		"enemy_poison": "%s 受到 %d 点毒伤",
		"enemy_attacks": "%s 攻击造成 %d 点伤害 (%d 被挡)",
		"you_fell": "你倒下了...",
		"victory": "胜利!",
		"poison_applied": "敌人中毒，每回合2点!",
		"reflect": "反弹下次攻击的50%!",
		"dodge_ready": "准备闪避下一次攻击!",
		"you_dodged": "你闪避了这次攻击!",
		"strength_gain": "获得 %d 点力量!",
		"reflect_hits": "反弹造成 %d 点伤害!",
		"enemy_gains_strength": "%s 获得 %d 点力量",
		"stats": "生命: %d/%d | 金币: %d",
		"deck_info": "牌组: %d | 骰子: %d",
		"legend": "👹敌人  💀精英  👑Boss  💎宝箱  🔥休息  🛒商店  ❓事件",
		"menu": "菜单",
		"version": "v0.1 alpha",
		# Card names
		"card_strike": "斩击",
		"card_heavy_strike": "重击",
		"card_block": "格挡",
		"card_fortress": "堡垒",
		"card_fireball": "火球术",
		"card_ice_shard": "冰晶",
		"card_heal": "治疗",
		"card_regenerate": "再生",
		"card_lucky_roll": "幸运骰",
		"card_loaded_dice": "灌铅骰",
		"card_poison_strike": "毒击",
		"card_mirror_shield": "镜盾",
		# Enemy names
		"enemy_slime": "史莱姆",
		"enemy_skeleton": "骷髅兵",
		"enemy_bat": "蝙蝠",
		"enemy_goblin": "哥布林",
		"enemy_ghost": "幽灵",
		"enemy_demon": "恶魔领主",
		"enemy_mushroom": "毒蘑菇",
		"enemy_mimic": "宝箱怪",
		"enemy_fire_elemental": "火元素",
		"enemy_dark_knight": "暗黑骑士",
		"enemy_ice_golem": "冰魔像",
		# Dice names
		"dice_normal": "普通骰",
		"dice_fire": "火焰骰",
		"dice_ice": "寒冰骰",
		"dice_poison": "剧毒骰",
		# New card names
		"card_flurry": "连击",
		"card_chain_lightning": "连锁闪电",
		"card_battle_cry": "战吼",
		"card_vampiric_strike": "吸血打击",
		"card_weaken": "削弱",
		"card_dodge_roll": "闪避翻滚",
		"card_inferno": "炼狱",
		"card_summon_familiar": "召唤使魔",
		"card_double_or_nothing": "孤注一掷",
		"card_curse_of_pain": "痛苦诅咒",
		# Relic names
		"relic_lucky_coin_name": "幸运金币",
		"relic_lucky_coin_desc": "20%几率打牌不消耗能量",
		"relic_blood_vial_name": "血瓶",
		"relic_blood_vial_desc": "最大生命+10，每回合恢复2点",
		"relic_iron_crown_name": "铁王冠",
		"relic_iron_crown_desc": "每回合开始获得3点护甲",
		"relic_flame_ring_name": "烈焰之戒",
		"relic_flame_ring_desc": "获得火焰骰，攻击+2伤害",
		"relic_frost_amulet_name": "霜冻护符",
		"relic_frost_amulet_desc": "获得寒冰骰，受到伤害-1",
		"relic_poison_fang_name": "毒牙",
		"relic_poison_fang_desc": "获得剧毒骰",
		"relic_war_drum_name": "战鼓",
		"relic_war_drum_desc": "连击加成翻倍",
		"relic_crystal_ball_name": "水晶球",
		"relic_crystal_ball_desc": "每回合多抽1张牌",
		"relic_broken_mirror_name": "碎镜",
		"relic_broken_mirror_desc": "10%几率伤害翻倍",
		"relic_golden_dice_name": "黄金骰",
		"relic_golden_dice_desc": "骰子最低点数为3",
		# Status effects
		"status_burn": "灼烧",
		"status_freeze": "冻结",
		"status_poison": "中毒",
		"status_weak": "虚弱",
		"status_strength": "力量",
		"status_vulnerable": "易伤",
		"status_regen": "再生",
		"status_combo": "连击",
		"status_dodge": "闪避",
		"status_shield": "护盾",
		# Battle messages
		"combo_bonus": "连击x%d! +%d加成",
		"relic_found": "获得遗物: %s",
		"card_upgraded": "%s 已升级!",
		"familiar_attacks": "使魔造成 %d 点伤害",
		"enemy_intent_attack": "意图: 攻击 %d",
		"enemy_intent_defend": "意图: 防御",
		"enemy_intent_buff": "意图: 增益",
		"enemy_intent_debuff": "意图: 减益",
		"enemy_intent_special": "意图: 蓄力!",
		"upgrade_prompt": "选择一张牌升级:",
		"relic_choose": "选择一个遗物:",
		"survivor_mode": "幸存者模式",
		"wave": "第 %d 波",
		"shop": "商店",
		# Shop UI
		"shop_title": "🛒 商店",
		"shop_gold": "💰 金币: %d",
		"shop_cards_section": "购买卡牌",
		"shop_relics_section": "购买遗物",
		"shop_buy_card": "%s (%d⚡) — %dG",
		"shop_buy_relic": "%s %s — %dG",
		"shop_remove_card": "🗑️ 删除一张牌 (%dG)",
		"shop_heal": "❤️ 恢复30%%生命 (%dG)",
		"shop_sold": "已购买 ✓",
		"shop_leave": "离开商店",
		"shop_no_relics": "遗物已收齐!",
		# Treasure UI
		"treasure_title": "💎 宝箱!",
		"treasure_gold_found": "发现 %d 金币!",
		"treasure_choose_card": "选择一张卡牌带走:",
		"treasure_dice_found": "获得 %s!",
		"treasure_skip": "跳过",
		"treasure_take": "收下",
		"treasure_continue": "继续",
		# Rest site UI
		"rest_title": "⛺ 休息点",
		"rest_heal": "❤️ 休息回复",
		"rest_heal_desc": "恢复 %d 点生命 (30%%)",
		"rest_upgrade": "⬆️ 升级卡牌",
		"rest_upgrade_desc": "选择一张牌 +2 基础值",
		"rest_pick_card": "选择要升级的卡牌:",
		"rest_upgraded": "%s 已升级! (+2 基础值)",
		# Event UI
		"event_title": "❓ 神秘事件",
		"event_leave": "离开",
		"event_continue": "继续",
		# Fountain
		"event_fountain_title": "⛲ 神秘泉水",
		"event_fountain_desc": "一汪闪烁的泉水。喝下去可能恢复体力...也可能有毒。",
		"event_fountain_drink": "🥤 喝一口",
		"event_fountain_good": "✨ 甘甜的泉水! 恢复 %d 点生命",
		"event_fountain_bad": "🤢 有毒! 受到 %d 点伤害",
		# Altar
		"event_altar_title": "🗿 远古祭坛",
		"event_altar_desc": "献祭一张卡牌，另一张将获得双倍强化。",
		"event_altar_step1": "选择要献祭的卡牌:",
		"event_altar_step2": "🗿 选择要强化的卡牌 (+4基础值)",
		"event_altar_no_cards": "你的牌组太小了，无法献祭。",
		# Cursed Chest
		"event_cursed_title": "💀 诅咒宝箱",
		"event_cursed_desc": "承受 %d 点伤害，获得一张强化过的 %s",
		"event_cursed_open": "🔓 打开",
		# Training
		"event_training_title": "🎯 训练场",
		"event_training_desc": "训练使你更强: 最大能量+1，随机一张牌升级。",
		"event_training_train": "⚔️ 训练",
		# Fortune
		"event_fortune_title": "🔮 占卜师",
		"event_fortune_desc": "命运的馈赠——选择你的奖赏。",
		"event_fortune_dice": "🎲 获得 %s",
		"event_fortune_gold": "💰 获得 %d 金币",
		# Forge
		"event_forge_title": "🔨 废弃锻造炉",
		"event_forge_desc": "将一张卡牌投入炉火，它将化为另一张未知的卡牌。",
		# Wanderer
		"event_wanderer_title": "👻 游荡之灵",
		"event_wanderer_desc": "一缕幽灵向你伸出手，似乎想要给你什么...",
		"event_wanderer_hp": "❤️ 最大生命+8",
		"event_wanderer_relic": "🏺 获得 %s",
		"event_wanderer_gold": "💰 获得 40 金币",
		# Relic choice UI
		"relic_choice_title": "🏺 选择一件遗物",
		"relic_choice_skip": "放弃",
		# Battle rewards UI
		"rewards_title": "⚔️ 战斗胜利!",
		"rewards_gold": "💰 +%d 金币",
		"rewards_card": "🃏 获得 %s",
		"rewards_dice": "🎲 获得 %s",
		"rewards_continue": "继续",
		# Card removal
		"remove_card_title": "🗑️ 选择要删除的卡牌",
		"remove_card_confirm": "删除 %s?",
		# Continue / Meta
		"continue_run": "▶ 继续冒险",
		"meta_stats": "共 %d 次冒险 | 最远到达第 %d 层",
		# Deck viewer
		"deck_viewer_btn": "📋 牌组",
		"deck_viewer_title": "📋 牌组与装备",
		"deck_tab_cards": "🃏 卡牌",
		"deck_tab_relics": "🏺 遗物",
		"deck_tab_stats": "📊 数据",
		"deck_total_cards": "共 %d 张牌",
		"deck_total_relics": "共 %d 件遗物",
		"deck_no_relics": "还没有遗物",
		"deck_dice_pool": "🎲 骰子池 (%d 颗)",
		# Run stats
		"stat_floor": "层数",
		"stat_time": "用时",
		"stat_enemies_killed": "击杀敌人",
		"stat_cards_played": "出牌次数",
		"stat_damage_dealt": "造成伤害",
		"stat_damage_taken": "承受伤害",
		"stat_healed": "恢复生命",
		"stat_gold_earned": "获得金币",
		"stat_dice_rolled": "掷骰次数",
		"stat_rooms_cleared": "清理房间",
		"stat_relics_found": "获得遗物",
		"stat_highest_combo": "最高连击",
		"stat_cards_upgraded": "升级卡牌",
		"victory_summary": "⚔️ 通关统计",
		# Boss phases
		"boss_phase2": "🔥 恶魔领主进入狂暴! 攻防大幅提升!",
		"boss_phase3": "💀 恶魔领主陷入绝望! 释放末日之力!",
		# Pause menu
		"pause_title": "⏸ 暂停",
		"pause_resume": "▶ 继续游戏",
		"pause_restart": "🔄 重新开始",
		"pause_quit": "🚪 退出到主菜单",
	},
	"en": {
		"title": "DICE & DESTINY",
		"subtitle": "骰运牌途",
		"desc": "A Roguelike Card-Dice Battler",
		"begin": "Begin Adventure",
		"settings": "Settings",
		"quit": "Quit",
		"settings_title": "Settings",
		"display_mode": "Display Mode",
		"fullscreen": "Fullscreen",
		"windowed": "Windowed",
		"language": "Language",
		"back": "Back",
		"end_turn": "End Turn [E]",
		"hand": "Hand:",
		"dice_pool": "Dice Pool:",
		"floor": "Floor %d / %d",
		"hp": "HP",
		"energy": "Energy: %d/%d",
		"armor": "Armor: %d",
		"victory_title": "VICTORY!",
		"victory_sub": "The Demon Lord has been vanquished!",
		"game_over": "GAME OVER",
		"retry": "Try Again",
		"main_menu": "Main Menu",
		"battle_log_turn": "=== Turn %d ===",
		"not_enough_energy": "Not enough energy!",
		"deals_damage": "%s deals %d damage! (dice: +%d)",
		"gains_armor": "%s grants %d armor (dice: +%d)",
		"fireball_hits": "Fireball hits all for %d! (dice: +%d)",
		"ice_shard_hits": "Ice Shard: %d damage + freeze! (dice: +%d)",
		"healed": "Healed %d HP (dice: +%d)",
		"regen": "Regenerating %d HP/turn for 3 turns",
		"reroll": "Re-rolled all dice with +%d bonus!",
		"loaded": "Set a die to 6!",
		"enemy_frozen": "%s is frozen!",
		"enemy_poison": "%s takes %d poison damage",
		"enemy_attacks": "%s attacks for %d (%d blocked)",
		"you_fell": "You have fallen...",
		"victory": "Victory!",
		"poison_applied": "Enemy poisoned for 2/turn!",
		"reflect": "Reflecting 50% of next attack!",
		"dodge_ready": "Ready to dodge the next attack!",
		"you_dodged": "You dodged the attack!",
		"strength_gain": "Gained %d Strength!",
		"reflect_hits": "Reflect deals %d damage!",
		"enemy_gains_strength": "%s gains %d Strength",
		"stats": "HP: %d/%d | Gold: %d",
		"deck_info": "Deck: %d | Dice: %d",
		"legend": "👹Enemy  💀Elite  👑Boss  💎Treasure  🔥Rest  🛒Shop  ❓Event",
		"menu": "Menu",
		"version": "v0.1 alpha",
		# Card names
		"card_strike": "Strike",
		"card_heavy_strike": "Heavy Strike",
		"card_block": "Block",
		"card_fortress": "Fortress",
		"card_fireball": "Fireball",
		"card_ice_shard": "Ice Shard",
		"card_heal": "Heal",
		"card_regenerate": "Regenerate",
		"card_lucky_roll": "Lucky Roll",
		"card_loaded_dice": "Loaded Dice",
		"card_poison_strike": "Poison Strike",
		"card_mirror_shield": "Mirror Shield",
		# Enemy names
		"enemy_slime": "Slime",
		"enemy_skeleton": "Skeleton",
		"enemy_bat": "Bat",
		"enemy_goblin": "Goblin",
		"enemy_ghost": "Ghost",
		"enemy_demon": "Demon Lord",
		"enemy_mushroom": "Poison Mushroom",
		"enemy_mimic": "Mimic",
		"enemy_fire_elemental": "Fire Elemental",
		"enemy_dark_knight": "Dark Knight",
		"enemy_ice_golem": "Ice Golem",
		# Dice names
		"dice_normal": "Normal Die",
		"dice_fire": "Fire Die",
		"dice_ice": "Ice Die",
		"dice_poison": "Poison Die",
		# New card names
		"card_flurry": "Flurry",
		"card_chain_lightning": "Chain Lightning",
		"card_battle_cry": "Battle Cry",
		"card_vampiric_strike": "Vampiric Strike",
		"card_weaken": "Weaken",
		"card_dodge_roll": "Dodge Roll",
		"card_inferno": "Inferno",
		"card_summon_familiar": "Summon Familiar",
		"card_double_or_nothing": "Double or Nothing",
		"card_curse_of_pain": "Curse of Pain",
		# Relic names
		"relic_lucky_coin_name": "Lucky Coin",
		"relic_lucky_coin_desc": "20% chance to not spend energy on cards",
		"relic_blood_vial_name": "Blood Vial",
		"relic_blood_vial_desc": "+10 Max HP, heal 2 per turn",
		"relic_iron_crown_name": "Iron Crown",
		"relic_iron_crown_desc": "Gain 3 armor at start of each turn",
		"relic_flame_ring_name": "Flame Ring",
		"relic_flame_ring_desc": "Gain Fire Die, +2 attack damage",
		"relic_frost_amulet_name": "Frost Amulet",
		"relic_frost_amulet_desc": "Gain Ice Die, -1 incoming damage",
		"relic_poison_fang_name": "Poison Fang",
		"relic_poison_fang_desc": "Gain Poison Die",
		"relic_war_drum_name": "War Drum",
		"relic_war_drum_desc": "Combo bonus doubled",
		"relic_crystal_ball_name": "Crystal Ball",
		"relic_crystal_ball_desc": "Draw 1 extra card per turn",
		"relic_broken_mirror_name": "Broken Mirror",
		"relic_broken_mirror_desc": "10% chance to double damage",
		"relic_golden_dice_name": "Golden Dice",
		"relic_golden_dice_desc": "Minimum dice roll is 3",
		# Status effects
		"status_burn": "Burn",
		"status_freeze": "Freeze",
		"status_poison": "Poison",
		"status_weak": "Weak",
		"status_strength": "Strength",
		"status_vulnerable": "Vulnerable",
		"status_regen": "Regen",
		"status_combo": "Combo",
		"status_dodge": "Dodge",
		"status_shield": "Shield",
		# Battle messages
		"combo_bonus": "Combo x%d! +%d bonus",
		"relic_found": "Relic found: %s",
		"card_upgraded": "%s upgraded!",
		"familiar_attacks": "Familiar deals %d damage",
		"enemy_intent_attack": "Intent: Attack %d",
		"enemy_intent_defend": "Intent: Defend",
		"enemy_intent_buff": "Intent: Buff",
		"enemy_intent_debuff": "Intent: Debuff",
		"enemy_intent_special": "Intent: Charging!",
		"upgrade_prompt": "Choose a card to upgrade:",
		"relic_choose": "Choose a relic:",
		"survivor_mode": "Survivor Mode",
		"wave": "Wave %d",
		"shop": "Shop",
		# Shop UI
		"shop_title": "🛒 Shop",
		"shop_gold": "💰 Gold: %d",
		"shop_cards_section": "Buy Cards",
		"shop_relics_section": "Buy Relics",
		"shop_buy_card": "%s (%d⚡) — %dG",
		"shop_buy_relic": "%s %s — %dG",
		"shop_remove_card": "🗑️ Remove a Card (%dG)",
		"shop_heal": "❤️ Heal 30%% HP (%dG)",
		"shop_sold": "Purchased ✓",
		"shop_leave": "Leave Shop",
		"shop_no_relics": "All relics collected!",
		# Treasure UI
		"treasure_title": "💎 Treasure!",
		"treasure_gold_found": "Found %d gold!",
		"treasure_choose_card": "Choose a card to take:",
		"treasure_dice_found": "Got %s!",
		"treasure_skip": "Skip",
		"treasure_take": "Take",
		"treasure_continue": "Continue",
		# Rest site UI
		"rest_title": "⛺ Rest Site",
		"rest_heal": "❤️ Rest & Heal",
		"rest_heal_desc": "Restore %d HP (30%%)",
		"rest_upgrade": "⬆️ Upgrade Card",
		"rest_upgrade_desc": "Pick a card: +2 base value",
		"rest_pick_card": "Choose a card to upgrade:",
		"rest_upgraded": "%s upgraded! (+2 base value)",
		# Event UI
		"event_title": "❓ Mysterious Event",
		"event_leave": "Leave",
		"event_continue": "Continue",
		# Fountain
		"event_fountain_title": "⛲ Mysterious Fountain",
		"event_fountain_desc": "A shimmering pool of water. Drink it? It might heal you... or not.",
		"event_fountain_drink": "🥤 Drink",
		"event_fountain_good": "✨ Refreshing! Healed %d HP",
		"event_fountain_bad": "🤢 Poisoned! Took %d damage",
		# Altar
		"event_altar_title": "🗿 Ancient Altar",
		"event_altar_desc": "Sacrifice a card to upgrade another one twice.",
		"event_altar_step1": "Choose a card to sacrifice:",
		"event_altar_step2": "🗿 Choose a card to empower (+4 base value)",
		"event_altar_no_cards": "Your deck is too small to sacrifice.",
		# Cursed Chest
		"event_cursed_title": "💀 Cursed Chest",
		"event_cursed_desc": "Take %d damage to receive an upgraded %s",
		"event_cursed_open": "🔓 Open It",
		# Training
		"event_training_title": "🎯 Training Grounds",
		"event_training_desc": "Training makes you stronger: +1 max energy and a random card upgrade.",
		"event_training_train": "⚔️ Train",
		# Fortune
		"event_fortune_title": "🔮 Fortune Teller",
		"event_fortune_desc": "A gift from fate — choose your reward.",
		"event_fortune_dice": "🎲 Get %s",
		"event_fortune_gold": "💰 Get %d gold",
		# Forge
		"event_forge_title": "🔨 Abandoned Forge",
		"event_forge_desc": "Throw a card into the flames. It will become something else entirely.",
		# Wanderer
		"event_wanderer_title": "👻 Wandering Spirit",
		"event_wanderer_desc": "A ghostly figure reaches out to you, offering a gift...",
		"event_wanderer_hp": "❤️ +8 Max HP",
		"event_wanderer_relic": "🏺 Get %s",
		"event_wanderer_gold": "💰 Get 40 gold",
		# Relic choice UI
		"relic_choice_title": "🏺 Choose a Relic",
		"relic_choice_skip": "Skip",
		# Battle rewards UI
		"rewards_title": "⚔️ Battle Won!",
		"rewards_gold": "💰 +%d gold",
		"rewards_card": "🃏 Got %s",
		"rewards_dice": "🎲 Got %s",
		"rewards_continue": "Continue",
		# Card removal
		"remove_card_title": "🗑️ Choose a Card to Remove",
		"remove_card_confirm": "Remove %s?",
		# Continue / Meta
		"continue_run": "▶ Continue Run",
		"meta_stats": "%d runs | Best: Floor %d",
		# Deck viewer
		"deck_viewer_btn": "📋 Deck",
		"deck_viewer_title": "📋 Deck & Equipment",
		"deck_tab_cards": "🃏 Cards",
		"deck_tab_relics": "🏺 Relics",
		"deck_tab_stats": "📊 Stats",
		"deck_total_cards": "%d cards in deck",
		"deck_total_relics": "%d relics",
		"deck_no_relics": "No relics yet",
		"deck_dice_pool": "🎲 Dice Pool (%d)",
		# Run stats
		"stat_floor": "Floor",
		"stat_time": "Time",
		"stat_enemies_killed": "Enemies Killed",
		"stat_cards_played": "Cards Played",
		"stat_damage_dealt": "Damage Dealt",
		"stat_damage_taken": "Damage Taken",
		"stat_healed": "HP Healed",
		"stat_gold_earned": "Gold Earned",
		"stat_dice_rolled": "Dice Rolled",
		"stat_rooms_cleared": "Rooms Cleared",
		"stat_relics_found": "Relics Found",
		"stat_highest_combo": "Highest Combo",
		"stat_cards_upgraded": "Cards Upgraded",
		"victory_summary": "⚔️ Run Complete",
		# Boss phases
		"boss_phase2": "🔥 The Demon Lord enters a frenzy! Attack & defense surges!",
		"boss_phase3": "💀 The Demon Lord is desperate! Unleashing doomsday power!",
		# Pause menu
		"pause_title": "⏸ Paused",
		"pause_resume": "▶ Resume",
		"pause_restart": "🔄 Restart",
		"pause_quit": "🚪 Quit to Menu",
	}
}

func t(key: String) -> String:
	if strings.has(current_lang) and strings[current_lang].has(key):
		return strings[current_lang][key]
	if strings["en"].has(key):
		return strings["en"][key]
	return key

func has_key(key: String) -> bool:
	return (strings.has(current_lang) and strings[current_lang].has(key)) or strings["en"].has(key)

func tf(key: String, args: Array) -> String:
	var template = t(key)
	return template % args
